version: '3'
services:
  web:
    build: .
    ports:
      - 8001:8000
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: findhireme
      MYSQL_USER: root
      MYSQL_PASSWORD: change-me
    ports:
      - 3306:3306